# Generated by Django 4.1.7 on 2024-02-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_employeetable_employee_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave_request',
            name='notify',
        ),
        migrations.AlterField(
            model_name='leave_request',
            name='status',
            field=models.CharField(default='Pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='leavetype_with_leavebalance',
            name='Bereavement_Leave',
            field=models.IntegerField(default=10, null=True),
        ),
        migrations.AlterField(
            model_name='leavetype_with_leavebalance',
            name='Custom_Festival_Leave',
            field=models.IntegerField(default=10, null=True),
        ),
        migrations.AlterField(
            model_name='leavetype_with_leavebalance',
            name='Leave_Without_Pay',
            field=models.IntegerField(default=10, null=True),
        ),
        migrations.AlterField(
            model_name='leavetype_with_leavebalance',
            name='Privilege_Leave',
            field=models.IntegerField(default=10, null=True),
        ),
    ]
