# Generated by Django 4.1.7 on 2024-02-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_recruitmentsystem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentsystem',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
