# Generated by Django 4.1.7 on 2024-02-16 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_recruitmentsystem_role_interview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitmentsystem',
            name='role',
        ),
    ]
